# Generated by Django 6.0.5 on 2026-05-12 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва обладнання (OLT/Switch)')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP-адреса')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC-адреса')),
                ('location', models.CharField(max_length=255, verbose_name='Фізичне розташування (Вузол)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус (Online)')),
            ],
            options={
                'verbose_name': 'Обладнання',
                'verbose_name_plural': 'Обладнання',
            },
        ),
    ]
