# Generated by Django 6.0.5 on 2026-05-12 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ клієнта')),
                ('contract_number', models.CharField(max_length=20, unique=True, verbose_name='Номер договору')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса підключення')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('is_online', models.BooleanField(default=False, verbose_name='Статус ONU (Online)')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.equipment', verbose_name='Підключено до обладнання')),
            ],
            options={
                'verbose_name': 'Абонент',
                'verbose_name_plural': 'Абоненти',
            },
        ),
    ]
