# Generated by Django 6.0.5 on 2026-05-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='onu_serial',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Серійний номер ONU'),
        ),
    ]
