# Generated by Django 6.0.5 on 2026-05-12 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_client_onu_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Опис проблеми')),
                ('status', models.CharField(choices=[('new', 'Нова'), ('process', 'В роботі'), ('closed', 'Виконана')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий')], default='medium', max_length=20, verbose_name='Пріоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='infrastructure.client', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Заявка на ремонт',
                'verbose_name_plural': 'Заявки на ремонт',
            },
        ),
    ]
