# Generated by Django 6.0.5 on 2026-05-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта (Lat)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота (Lng)'),
        ),
    ]
