# Generated by Django 6.0.5 on 2026-05-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0005_equipment_latitude_equipment_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва товару (Модель)')),
                ('category', models.CharField(choices=[('cable', 'Кабель (Оптика / Вита пара)'), ('onu', 'Абонентські термінали (ONU)'), ('router', 'Wi-Fi Роутери'), ('switch', 'Комутатори / Світчі'), ('tools', 'Інструменти / Витратні матеріали')], max_length=20, verbose_name='Категорія')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість на складі')),
                ('unit', models.CharField(choices=[('pcs', 'шт.'), ('meters', 'м.')], default='pcs', max_length=10, verbose_name='Одиниця виміру')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Останнє оновлення')),
            ],
            options={
                'verbose_name': 'Складська позиція',
                'verbose_name_plural': 'Складський облік',
            },
        ),
    ]
