# Generated by Django 6.0.5 on 2026-05-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0006_warehouseitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема повідомлення')),
                ('text', models.TextField(verbose_name='Текст повідомлення')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата та час відправки')),
                ('target_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.client', verbose_name='Кому (Абонент)')),
            ],
            options={
                'verbose_name': 'Журнал повідомлень',
                'verbose_name_plural': 'Журнал повідомлень',
            },
        ),
    ]
