# Generated by Django 6.0.5 on 2026-05-13 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0007_messagelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва тарифу')),
                ('price', models.IntegerField(verbose_name='Ціна (грн/міс)')),
                ('speed', models.IntegerField(verbose_name='Швидкість (Мбіт/сек)')),
                ('channels', models.CharField(max_length=50, verbose_name='Кількість каналів')),
                ('dynamic_ip', models.BooleanField(default=True, verbose_name='Динамічний білий IP')),
                ('kinoman', models.BooleanField(default=True, verbose_name='Кіноман')),
                ('support_24_7', models.BooleanField(default=True, verbose_name='Підтримка 24/7')),
                ('connection_fee', models.IntegerField(default=1, verbose_name='Вартість підключення (грн)')),
                ('is_promo', models.BooleanField(default=False, verbose_name='Акційний тариф')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифи',
            },
        ),
    ]
