# Generated by Django 6.0.5 on 2026-05-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0008_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ співробітника')),
                ('position', models.CharField(choices=[('admin', 'Системний адміністратор'), ('installer', 'Монтажник'), ('operator', 'Оператор Колл-центру'), ('foreman', 'Бригадир'), ('director', 'Директор')], max_length=20, verbose_name='Посада')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=20, verbose_name='Основний телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний співробітник')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Персонал',
            },
        ),
    ]
