# Generated by Django 6.0.5 on 2026-05-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0009_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('city', models.CharField(choices=[('м. Васильків', 'м. Васильків'), ('с. Барахти', 'с. Барахти'), ('с. Березанщина', 'с. Березанщина'), ("с. Безп'ятне", "с. Безп'ятне"), ('с. Борисів', 'с. Борисів'), ('с. Залізне', 'с. Залізне'), ('с. Заріччя', 'с. Заріччя'), ('с. Застугна', 'с. Застугна'), ('с. Здорівка', 'с. Здорівка'), ('с. Зелений Бір', 'с. Зелений Бір'), ('с. Кобці', 'с. Кобці'), ('с. Крушинка', 'с. Крушинка'), ('с. Крячки', 'с. Крячки'), ('с. Кулибаба', 'с. Кулибаба'), ("с. Луб'янка", "с. Луб'янка"), ('с. Погреби', 'с. Погреби'), ('с. Путрівка', 'с. Путрівка'), ('с. Червоне', 'с. Червоне'), ('с. Копачів', 'с. Копачів'), ('с. Мала Бугаївка', 'с. Мала Бугаївка'), ('с. Велика Бугаївка', 'с. Велика Бугаївка'), ('с. Застугна (біля Копачів)', 'с. Застугна (біля Копачів)'), ('Інше', 'Інше місто')], max_length=50, verbose_name='Місто/Село')),
                ('object_type', models.CharField(choices=[('house', 'Будинок'), ('apartment', 'Квартира')], max_length=20, verbose_name="Тип об'єкта")),
                ('street', models.CharField(max_length=100, verbose_name='Вулиця')),
                ('house_number', models.CharField(max_length=20, verbose_name='Номер будинку')),
                ('apartment_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира')),
                ('entrance', models.CharField(blank=True, max_length=10, null=True, verbose_name="Під'їзд")),
                ('floor', models.CharField(blank=True, max_length=10, null=True, verbose_name='Поверх')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('status', models.CharField(choices=[('new', 'Нова (Передати технікам)'), ('in_progress', 'В роботі'), ('connected', 'Підключено'), ('canceled', 'Скасовано')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Заявка на підключення',
                'verbose_name_plural': 'Заявки на підключення',
            },
        ),
    ]
