# Generated by Django 6.0.5 on 2026-05-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0010_connectionapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectionapplication',
            name='status',
            field=models.CharField(choices=[('no_answer', 'Не відповідає'), ('thinking', 'Міркує'), ('call_back', 'Сам Зателефонує'), ('agreed', 'Згодний(-на)'), ('connected', 'Підключений(-на)'), ('refusal', 'Відмова')], default='thinking', max_length=20, verbose_name='Статус'),
        ),
    ]
