# Generated by Django 6.0.5 on 2026-05-25 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0011_alter_connectionapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.employee', verbose_name='Призначений монтажник'),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Запланована дата підключення'),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='tech_details',
            field=models.TextField(blank=True, null=True, verbose_name='Технічні дані (геолокація, тариф)'),
        ),
    ]
