# Generated by Django 6.0.5 on 2026-05-25 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_connectionapplication_assignee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionapplication',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='connectionapplication',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='connectionapplication',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='connection_fee',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='dynamic_ip',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='kinoman',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='support_24_7',
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='task_type',
            field=models.CharField(choices=[('connection', 'Нове підключення'), ('repair', 'Ремонт'), ('magistral', 'Магістраль'), ('audit', 'Перевірка'), ('cctv', 'Відеонагляд'), ('other', 'Інше')], default='connection', max_length=20, verbose_name='Тип завдання'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.employee', verbose_name='Виконавець'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='city',
            field=models.CharField(choices=[('м. Васильків', 'м. Васильків'), ('с. Барахти', 'с. Барахти'), ('с. Березанщина', 'с. Березанщина'), ("с. Безп'ятне", "с. Безп'ятне"), ('с. Борисів', 'с. Борисів'), ('с. Залізне', 'с. Залізне'), ('с. Заріччя', 'с. Заріччя'), ('с. Застугна', 'с. Застугна'), ('с. Здорівка', 'с. Здорівка'), ('с. Зелений Бір', 'с. Зелений Бір'), ('с. Кобці', 'с. Кобці'), ('с. Крушинка', 'с. Крушинка'), ('с. Крячки', 'с. Крячки'), ('с. Кулибаба', 'с. Кулибаба'), ("с. Луб'янка", "с. Луб'янка"), ('с. Погреби', 'с. Погреби'), ('с. Путрівка', 'с. Путрівка'), ('с. Червоне', 'с. Червоне'), ('с. Копачів', 'с. Копачів'), ('с. Мала Бугаївка', 'с. Мала Бугаївка'), ('с. Велика Бугаївка', 'с. Велика Бугаївка'), ('с. Застугна (біля Копачів)', 'с. Застугна (біля Копачів)'), ('Інше', 'Інше місто')], max_length=50, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='house_number',
            field=models.CharField(max_length=20, verbose_name='№ будинку'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='object_type',
            field=models.CharField(max_length=20, verbose_name="Тип об'єкта"),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('thinking', 'Міркує'), ('agreed', 'Згодний'), ('connected', 'Підключений'), ('refusal', 'Відмова')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='tech_details',
            field=models.TextField(blank=True, null=True, verbose_name='Технічні дані'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ПІБ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=50, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='target_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.client', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='channels',
            field=models.CharField(max_length=50, verbose_name='Канали'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='speed',
            field=models.IntegerField(verbose_name='Швидкість'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='category',
            field=models.CharField(choices=[('cable', 'Кабель'), ('onu', 'ONU'), ('router', 'Роутер'), ('switch', 'Світч'), ('tools', 'Інструменти')], max_length=20, verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Назва товару'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Кількість'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='unit',
            field=models.CharField(default='шт.', max_length=10, verbose_name='Одиниця'),
        ),
    ]
