# Generated by Django 6.0.5 on 2026-05-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0013_remove_connectionapplication_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Під'їзд"),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Поверх'),
        ),
    ]
