# Generated by Django 6.0.5 on 2026-05-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_connectionapplication_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активний'),
        ),
    ]
