# Generated by Django 6.0.5 on 2026-05-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0015_alter_employee_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionapplication',
            options={},
        ),
        migrations.RemoveField(
            model_name='connectionapplication',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='connectionapplication',
            name='entrance',
        ),
        migrations.RemoveField(
            model_name='connectionapplication',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='connectionapplication',
            name='task_type',
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Місто'),
        ),
    ]
