# Generated by Django 6.0.5 on 2026-05-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0017_alter_employee_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionapplication',
            options={'verbose_name': 'Заявка на підключення', 'verbose_name_plural': 'Заявки на підключення'},
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Квартира'),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='entrance',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="Під'їзд"),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='floor',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Поверх'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'Адмін'), ('installer', 'Монтажник')], max_length=50, verbose_name='Посада'),
        ),
    ]
