# Generated by Django 6.0.5 on 2026-05-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0018_alter_connectionapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='task_type',
            field=models.CharField(choices=[('connection', 'Нове підключення'), ('repair', 'Ремонт'), ('magistral', 'Магістраль'), ('audit', 'Перевірка'), ('cctv', 'Відеонагляд'), ('other', 'Інше')], default='connection', max_length=20, verbose_name='Тип завдання'),
        ),
        migrations.AlterField(
            model_name='connectionapplication',
            name='city',
            field=models.CharField(choices=[('м. Васильків', 'м. Васильків'), ('с. Барахти', 'с. Барахти'), ('с. Березанщина', 'с. Березанщина'), ("с. Безп'ятне", "с. Безп'ятне"), ('с. Борисів', 'с. Борисів'), ('с. Залізне', 'с. Залізне'), ('с. Заріччя', 'с. Заріччя'), ('с. Застугна', 'с. Застугна'), ('с. Здорівка', 'с. Здорівка'), ('с. Зелений Бір', 'с. Зелений Бір'), ('с. Кобці', 'с. Кобці'), ('с. Крушинка', 'с. Крушинка'), ('с. Крячки', 'с. Крячки'), ('с. Кулибаба', 'с. Кулибаба'), ("с. Луб'янка", "с. Луб'янка"), ('с. Погреби', 'с. Погреби'), ('с. Путрівка', 'с. Путрівка'), ('с. Червоне', 'с. Червоне'), ('с. Копачів', 'с. Копачів'), ('с. Мала Бугаївка', 'с. Мала Бугаївка'), ('с. Велика Бугаївка', 'с. Велика Бугаївка'), ('с. Застугна (біля Копачів)', 'с. Застугна (біля Копачів)'), ('Інше', 'Інше місто')], max_length=50, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'Системний адміністратор'), ('installer', 'Монтажник'), ('operator', 'Оператор Колл-центру'), ('foreman', 'Бригадир'), ('director', 'Директор')], max_length=50, verbose_name='Посада'),
        ),
    ]
