# Generated by Django 6.0.5 on 2026-05-28 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0021_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('category', models.CharField(choices=[('router', 'Роутер'), ('onu', 'ONU / GPON'), ('switch', 'Комутатор'), ('cable', 'Кабель'), ('accessory', 'Аксесуари'), ('ups', 'ДБЖ / Павербанк')], max_length=20, verbose_name='Категорія')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна (грн)')),
                ('quantity', models.IntegerField(default=0, verbose_name='Кількість на складі')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний для продажу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Додано')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Каталог товарів',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Кількість')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума (грн)')),
                ('buyer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='ПІБ покупця')),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон покупця')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('transfer', 'Переказ')], default='cash', max_length=20, verbose_name='Спосіб оплати')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Коментар')),
                ('sold_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажу')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='infrastructure.client', verbose_name='Абонент (якщо є)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='infrastructure.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продаж',
                'verbose_name_plural': 'Журнал продажів',
                'ordering': ['-sold_at'],
            },
        ),
    ]
