# Generated by Django 6.0.5 on 2026-05-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0023_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса аварії')),
                ('description', models.TextField(verbose_name='Опис проблеми (обрив/збій)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Нова'), ('in_progress', 'В роботі'), ('done', 'Виконано')], default='new', max_length=20)),
                ('assignees', models.ManyToManyField(related_name='emergency_tasks', to='infrastructure.employee', verbose_name='Монтажники')),
            ],
        ),
    ]
