# Generated by Django 6.0.5 on 2026-06-05 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0024_emergencytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокований'),
        ),
        migrations.AddField(
            model_name='client',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.tariff', verbose_name='Тариф'),
        ),
        migrations.CreateModel(
            name='ClientCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=7, unique=True, verbose_name='Логін (7 цифр)')),
                ('password', models.CharField(max_length=10, verbose_name='Пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='infrastructure.client', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Дані для кабінету',
                'verbose_name_plural': 'Дані для кабінету',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сума (грн)')),
                ('payment_type', models.CharField(choices=[('topup', 'Поповнення'), ('charge', 'Списання абонплати'), ('promised', 'Обіцяний платіж'), ('manual', 'Ручне коригування')], max_length=20, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('created_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ким проведено')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='infrastructure.client', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Платіж',
                'verbose_name_plural': 'Журнал платежів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromisedPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_at', models.DateTimeField(verbose_name='Діє до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promised_payments', to='infrastructure.client', verbose_name='Абонент')),
            ],
            options={
                'verbose_name': 'Обіцяний платіж',
                'verbose_name_plural': 'Обіцяні платежі',
            },
        ),
    ]
