# Generated by Django 6.0.5 on 2026-06-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0026_alter_client_options_alter_clientcredentials_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionapplication',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.employee', verbose_name='Виконавець'),
        ),
        migrations.AddField(
            model_name='connectionapplication',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Запланована дата'),
        ),
    ]
