# Generated by Django 6.0.5 on 2026-06-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0029_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('admin', 'Системний адміністратор'), ('installer', 'Монтажник'), ('operator', 'Оператор Колл-центру'), ('foreman', 'Бригадир'), ('director', 'Директор')], max_length=50, verbose_name='Посада'),
        ),
    ]
