# Generated by Django 6.0.5 on 2026-06-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0031_delete_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Рахунок абонента', 'verbose_name_plural': 'Рахунки абонентів'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Абонент', 'verbose_name_plural': 'Абоненти'},
        ),
        migrations.AlterModelOptions(
            name='clientcredentials',
            options={'verbose_name': 'Обліковий запис абонента', 'verbose_name_plural': 'Облікові записи абонентів'},
        ),
        migrations.AlterModelOptions(
            name='connectionapplication',
            options={'verbose_name': 'Заявка на підключення', 'verbose_name_plural': 'Заявки на підключення'},
        ),
        migrations.AlterModelOptions(
            name='emergencytask',
            options={'verbose_name': 'Аварія', 'verbose_name_plural': 'Аварії'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Співробітник', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Обладнання', 'verbose_name_plural': 'Обладнання'},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платіж', 'verbose_name_plural': 'Платежі'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='promisedpayment',
            options={'verbose_name': 'Обіцяний платіж', 'verbose_name_plural': 'Обіцяні платежі'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продаж', 'verbose_name_plural': 'Продажі'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифи'},
        ),
        migrations.AlterModelOptions(
            name='warehouseitem',
            options={'verbose_name': 'Складська позиція', 'verbose_name_plural': 'Складські позиції'},
        ),
    ]
